# Generated by Django 3.1.3 on 2023-04-12 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccode', models.CharField(max_length=10)),
                ('cname', models.CharField(max_length=20)),
                ('birth', models.IntegerField(max_length=12)),
                ('phoneNum', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=60)),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('sNo', models.AutoField(primary_key=True, serialize=False)),
                ('ccode', models.CharField(max_length=10)),
                ('cname', models.CharField(max_length=20)),
                ('sDate', models.DateTimeField(blank=True, null=True)),
                ('departure', models.CharField(max_length=60)),
                ('arrival', models.CharField(max_length=60)),
                ('fee', models.IntegerField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='')),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csms.customer')),
            ],
        ),
    ]
