# Generated by Django 3.1.3 on 2023-04-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='customer',
        ),
        migrations.AlterField(
            model_name='service',
            name='ccode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csms.customer'),
        ),
    ]
